### ISSUE TITLE
[Bug] Live version of this app is down

### ISSUE THREAD

**Issue by Ph0enixKM** [kudziajaroslaw98/flash-cards#28]
I wanted to check this app out, but it shows:
```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: fra1::2pzx8-1732096266949-3791bd3ff5d5
```
when entering https://flash-cards-sage.vercel.app url

**Comment by kudziajaroslaw98** [comment]
Readme wasn't changed when i moved the domain. Thanks for catching the bug. It's fixed now.

**Comment by lens0021** [comment]
There is another. ![Screenshot_20241121-172033~2](https://github.com/user-attachments/assets/7b7d53f9-e488-40a7-97da-da9d9cfc2721)

**Comment by kudziajaroslaw98** [comment]
Thank you. Indeed that was a mistake on my side. I haven't really used github for a while now. It's fixed now. Thank you once more
