### ISSUE TITLE
[Feature] OAuth integration

### ISSUE THREAD

**Issue by Ph0enixKM** [kudziajaroslaw98/flash-cards#35]
I hardly ever create an account with my email and password nowadays. OAuth comes with multiple benefits:
- **Safety** - it's much better for the user and the developer to maintain a secure way of signing in to the service. If just OAuth is supported on the website, then there is no need for SMTP email server since you don't have to validate the user - the OAuth service does.
- **Simplicity** - It's much simpler and quicker both for the user and the server to authenticate and becomes slowly [the preferred way to authenticate among consumers](https://en.wikipedia.org/wiki/Social_login?utm_source=chatgpt.com#Advantages_of_social_login).

Happy to see this website develop. I'd like to see some kind of better flashcard app arise 🙌

**Comment by Ph0enixKM** [comment]
@kudziajaroslaw98 Oh I just realized that the whole registration system isn't working yet

**Comment by kudziajaroslaw98** [comment]
Yes, oAuth is planned. It should be implemented in the upcoming week. Thank you for the suggestion @Ph0enixKM. 🫡

**Comment by kudziajaroslaw98** [comment]
@Ph0enixKM oAuth is implemented on main. (github/google). I have tested both.
